### PR TITLE
Basic security revisions

### PR DESCRIPTION
**Pull request by Calebrw**
Here are couple of basic security improvements.

### CODE REVIEW

**Comment by mariofont** [comment]
Nice! It looks like security won't be an issue now. I will merge this pull request into the master branch.

**Comment by Calebrw** [comment]
Please keep in mind that this is not a silver bullet to security. This is simply a large improvement to the security of the password portion of your application. I don't intend this to be the final be-all-end-all of this, but since you are making this public, I want to make sure that a potential end use is to have some rudimentary security.

**Comment by mariofont** [comment]
I will take your advice into account for my next projects, however, I don't think I'll use it here since I want to keep it very simple, for someone who has seen very little of PHP. If someone wants a bulletproof login system, they are definitely looking in the wrong place, this is just a quick, simple project. Having said that, thanks again.

**Comment by EmedBooks** [comment]
How to add new users to config.php?

**Pull request merged**
